import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: '"Every Author as First Author" Web API',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
